---
version: "3"

services:
  px-ui:
    image: ghcr.io/Artin-GH/px-ui:latest
    container_name: px-ui
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
